### ISSUE TITLE
More obvious method to close the flashlight app

### ISSUE THREAD

**Issue by jcstaudt** [AsteroidOS/asteroid-flashlight#1]
Leaving the Flashlight application isn't obvious. At first I tried to tap it "off" as somewhat customary in the world of smartphones.

The white screen must be swiped away for the application to close, but the white "directional arrows" are not visible on the white background when the flashlight application is active. Perhaps there should be a small "close" button, or that the directional arrows change color to have some contrast with the bright white screen.

**Comment by FlorentRevest** [comment]
Thank you for your suggestion :) Magnefire implemented a toggle mechanism that should help figure out how to leave the app
